# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
# highlighter : pygments
highlighter: rouge

# SEO settings
title: Luke Lecheler
description: "Personal site"
keywords: "luke lecheler, site"

# Site settings
# url: http://nandomoreira.me
# baseurl: "/dotX"
# baseurl: ""

# Author settings
author:
  name      : Luke Lecheler
  job       : Educational Technology
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://lecheler.github.io
  github    : http://github.com/lecheler
  twitter   : http://twitter.com/lukerighthere
  facebook  : http://facebook.com/lecheler
  linkedin  : https://www.linkedin.com/in/lecheler/

google_analytics: UA-101285807-1
repo: https://github.com/lecheler/lecheler.github.io

# comments
disqus_shortname: "fernandomoreira"
